mode:
  develop: true

server:
  port: 8090

db:
  dsn: "root:123456@tcp(localhost:3306)/gin?charset=utf8mb4&parseTime=True&loc=Local"
  maxIdleConn: 10 # 最大空闲连接数
  maxOpenConn: 10 # 最多打开连接数


redis:
  addr: "127.0.0.1:6379"

log:
  MaxSize: 5      # 日志文件最大的尺寸(M), 超限后开始自动分割
  MaxBackups: 10  # 保留旧文件的最大个数
  MaxAge: 90      # 保留旧文件的最大天数